#!/usr/bin/env bash
# SutazMail one-shot deployment: docker-mailserver + REST bridge + SutazMail + Postgres.
#
#   ./deploy.sh                          # interactive (asks domain + admin email)
#   MAIL_DOMAIN=example.com SUPERADMIN_EMAIL=you@example.com ./deploy.sh   # unattended
#
# Idempotent: re-running reuses the existing .env and skips completed steps.
# Requirements: docker with the compose v2 plugin, openssl, bash. Nothing else —
# node/bcrypt run inside throwaway containers.
set -euo pipefail
cd "$(dirname "$0")"

say()  { printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
ok()   { printf '\033[1;32mOK\033[0m  %s\n' "$*"; }
die()  { printf '\033[1;31mERROR\033[0m %s\n' "$*" >&2; exit 1; }

# ------------------------------------------------------------------ prerequisites
say "Checking prerequisites"
command -v docker >/dev/null || die "docker is not installed"
docker compose version >/dev/null 2>&1 || die "docker compose v2 plugin is not installed"
command -v openssl >/dev/null || die "openssl is not installed"
ok "docker, compose, openssl present"

DMS_IMAGE="ghcr.io/docker-mailserver/docker-mailserver:15.1.0"

# ------------------------------------------------------------------ configuration
if [ -f .env ]; then
  say "Reusing existing .env"
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
  CREDS_FILE="(existing .env — credentials file from the first run)"
else
  say "Generating configuration"
  MAIL_DOMAIN="${MAIL_DOMAIN:-}"
  SUPERADMIN_EMAIL="${SUPERADMIN_EMAIL:-}"
  if [ -z "$MAIL_DOMAIN" ]; then read -rp "Primary mail domain (e.g. example.com): " MAIL_DOMAIN; fi
  [ -n "$MAIL_DOMAIN" ] || die "MAIL_DOMAIN is required"
  MAIL_HOSTNAME="${MAIL_HOSTNAME:-mail.$MAIL_DOMAIN}"
  if [ -z "$SUPERADMIN_EMAIL" ]; then read -rp "Platform admin email (your login): " SUPERADMIN_EMAIL; fi
  [ -n "$SUPERADMIN_EMAIL" ] || die "SUPERADMIN_EMAIL is required"
  APP_HOST_PORT="${APP_HOST_PORT:-8095}"

  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  DMS_API_KEY=$(openssl rand -hex 32)
  SESSION_SECRET=$(openssl rand -hex 32)
  MASTER_SIEVE_PASSWORD=$(openssl rand -hex 16)
  SUPERADMIN_PASSWORD="${SUPERADMIN_PASSWORD:-$(openssl rand -base64 15 | tr '+/' 'Aa')}"
  POSTMASTER_PASSWORD=$(openssl rand -base64 15 | tr '+/' 'Aa')

  say "Hashing the admin password (bcrypt, in a throwaway node container)"
  SUPERADMIN_PASSWORD_HASH=$(docker run --rm -e P="$SUPERADMIN_PASSWORD" node:22-alpine sh -c \
    'cd /tmp && npm init -y >/dev/null 2>&1 && npm i bcryptjs >/dev/null 2>&1 && node -e "console.log(require(\"bcryptjs\").hashSync(process.env.P,12))"')
  [ -n "$SUPERADMIN_PASSWORD_HASH" ] || die "bcrypt hash generation failed"
  # docker-compose interpolates $ in .env files — escape as $$.
  HASH_ESCAPED=${SUPERADMIN_PASSWORD_HASH//$/\$\$}

  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
MAIL_DOMAIN=$MAIL_DOMAIN
MAIL_HOSTNAME=$MAIL_HOSTNAME
APP_HOST_PORT=$APP_HOST_PORT
WEBMAIL_URL=

POSTGRES_USER=sutazmail
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=sutazmail
DATABASE_URL=postgresql://sutazmail:$POSTGRES_PASSWORD@sutazmail-db:5432/sutazmail

MAILSERVER_API_URL=http://mailserver:8888
DMS_API_KEY=$DMS_API_KEY

MAILSERVER_SIEVE_HOST=mailserver
MAILSERVER_SIEVE_PORT=4190
MAILSERVER_TLS_SERVERNAME=$MAIL_HOSTNAME
MAILSERVER_TLS_REJECT_UNAUTHORIZED=0
MASTER_SIEVE_USER=sutazmail
MASTER_SIEVE_PASSWORD=$MASTER_SIEVE_PASSWORD

SUPERADMIN_EMAIL=$SUPERADMIN_EMAIL
SUPERADMIN_PASSWORD_HASH=$HASH_ESCAPED

SESSION_SECRET=$SESSION_SECRET
NODE_ENV=production
EOF
  chmod 600 .env

  CREDS_FILE="sutazmail-credentials-$(date +%Y%m%d-%H%M%S).txt"
  cat > "$CREDS_FILE" <<EOF
SutazMail deployment credentials — store these in your password manager, then delete this file.
Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

Admin console:      http://127.0.0.1:$APP_HOST_PORT  (put HTTPS reverse proxy in front)
Admin login:        $SUPERADMIN_EMAIL
Admin password:     $SUPERADMIN_PASSWORD

First mailbox:      postmaster@$MAIL_DOMAIN
Mailbox password:   $POSTMASTER_PASSWORD
EOF
  chmod 600 "$CREDS_FILE"
  export MAIL_DOMAIN MAIL_HOSTNAME APP_HOST_PORT POSTMASTER_PASSWORD MASTER_SIEVE_PASSWORD
  export MASTER_SIEVE_USER=sutazmail
  ok ".env written; credentials saved to $CREDS_FILE"
fi

APP_HOST_PORT="${APP_HOST_PORT:-8095}"
mkdir -p data/dms/mail-data data/dms/mail-state data/dms/mail-logs data/pgdata

# ------------------------------------------------- first mailbox (DMS boot requirement)
# docker-mailserver refuses to start with zero accounts, so bootstrap the account
# file into the config volume BEFORE the first compose up (official one-shot flow).
if [ ! -f dms-config/postfix-accounts.cf ] || ! grep -q "@" dms-config/postfix-accounts.cf 2>/dev/null; then
  say "Creating first mailbox postmaster@${MAIL_DOMAIN:?MAIL_DOMAIN missing}"
  POSTMASTER_PASSWORD="${POSTMASTER_PASSWORD:-$(openssl rand -base64 15 | tr '+/' 'Aa')}"
  docker run --rm -v "$(pwd)/dms-config:/tmp/docker-mailserver" "$DMS_IMAGE" \
    setup email add "postmaster@$MAIL_DOMAIN" "$POSTMASTER_PASSWORD"
  ok "postmaster@$MAIL_DOMAIN created"
else
  ok "mailbox accounts already present"
fi

# ------------------------------------------------------------------------ stack up
say "Building and starting the stack (first build takes a few minutes)"
docker compose up -d --build

say "Waiting for the mail server to become healthy"
for i in $(seq 1 60); do
  STATUS=$(docker inspect -f '{{.State.Health.Status}}' mailserver 2>/dev/null || echo starting)
  [ "$STATUS" = healthy ] && break
  sleep 5
done
[ "$(docker inspect -f '{{.State.Health.Status}}' mailserver)" = healthy ] || die "mailserver did not become healthy — check: docker compose logs mailserver"
ok "mailserver healthy"

# ----------------------------------------------------------- master sieve account
say "Ensuring the Dovecot master account (portal features act on behalf of mailboxes)"
if docker compose exec -T mailserver setup dovecot-master list 2>/dev/null | grep -q "^${MASTER_SIEVE_USER:-sutazmail}"; then
  ok "master account already present"
else
  docker compose exec -T mailserver setup dovecot-master add "${MASTER_SIEVE_USER:-sutazmail}" "${MASTER_SIEVE_PASSWORD:?MASTER_SIEVE_PASSWORD missing (see .env)}"
  ok "master account created"
fi

# ------------------------------------------------------------------------- DKIM
say "Ensuring DKIM keys for $MAIL_DOMAIN"
if docker compose exec -T mailserver sh -c "ls /tmp/docker-mailserver/rspamd/dkim/*${MAIL_DOMAIN}* >/dev/null 2>&1"; then
  ok "DKIM key already present"
else
  docker compose exec -T mailserver setup config dkim keysize 2048 domain "$MAIL_DOMAIN"
  docker compose exec -T mailserver supervisorctl restart rspamd >/dev/null 2>&1 || true
  ok "DKIM key generated"
fi

# --------------------------------------------------------------------- app health
say "Waiting for SutazMail"
for i in $(seq 1 24); do
  if curl -fsS "http://127.0.0.1:$APP_HOST_PORT/api/health" >/dev/null 2>&1; then break; fi
  sleep 5
done
curl -fsS "http://127.0.0.1:$APP_HOST_PORT/api/health" >/dev/null || die "app not healthy — check: docker compose logs sutazmail"
ok "SutazMail healthy at http://127.0.0.1:$APP_HOST_PORT"

# ------------------------------------------------------------------- DNS summary
say "DNS records to publish at your registrar"
echo "  MX    ${MAIL_DOMAIN}.           10 ${MAIL_HOSTNAME}."
echo "  TXT   ${MAIL_DOMAIN}.           \"v=spf1 mx ~all\""
echo "  TXT   _dmarc.${MAIL_DOMAIN}.    \"v=DMARC1; p=none; rua=mailto:postmaster@${MAIL_DOMAIN}\""
echo "  DKIM (TXT):"
docker compose exec -T mailserver sh -c "cat /tmp/docker-mailserver/rspamd/dkim/*${MAIL_DOMAIN}*.txt 2>/dev/null" || echo "  (DKIM record file not found — run: docker compose exec mailserver setup config dkim)"

say "Done"
cat <<EOF
Next steps:
  1. Log in at http://127.0.0.1:$APP_HOST_PORT with your admin email
     (credentials: $CREDS_FILE — move them to a password manager).
  2. Put an HTTPS reverse proxy (nginx/Caddy/Traefik) in front of port $APP_HOST_PORT.
  3. Publish the DNS records above, then set SSL_TYPE in mailserver.env
     (letsencrypt recommended) and re-run: docker compose up -d
  4. Add more domains and mailboxes from the SutazMail UI.
EOF
