#!/usr/bin/python3
# version=1.5.22

import http.server
import socketserver
import subprocess
import json
import os
import datetime

DMS_API_HOST = os.environ.get('DMS_API_HOST', '0.0.0.0')          # Listen on all available interfaces
DMS_API_PORT = int(os.environ.get('DMS_API_PORT', 8888))          # Port to listen on
DMS_API_KEY = os.environ.get('DMS_API_KEY', 'missing')            # generated by bms-gui on first start and added into DMS compose
DMS_API_SIZE = int(os.environ.get('DMS_API_SIZE', 1024))          # max bytes per request sent from dms-gui, prevents buffer overflow and other exploit mechanics
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'info')                   # relies on dms LOG_LEVEL value set in your 'mailserver.env'
timeout_default = 1                                               # can be superseeded by passed timeout in data

def logger(message):
  # 2025-11-05T15:05:49.710284+00:00 mx dms-gui-api:
  print(f'{datetime.datetime.now().astimezone().strftime("%Y-%m-%dT%H:%M:%S.%f%z")} {os.uname().nodename.split(".")[0]} dms-gui-api: {message}')

def debugg(message):
  if LOG_LEVEL == 'debug': logger(message)

class APIHandler(http.server.BaseHTTPRequestHandler):

  def do_POST(self):
    # 1. Get the content length from the headers
    api_key  = self.headers.get('Authorization', 'missing')
    content_length  = int(self.headers.get('Content-Length', 0))

    # 2. Read the raw POST data from the request body
    post_data = self.rfile.read(content_length)

    # 3. Attempt to parse the data as JSON
    try:
      # 4. Rejects content > DMS_API_SIZE
      if content_length > DMS_API_SIZE:
        response_message = {"status": "error", "error": "data recieved is too large"}
        logger(response_message['error'])

      json_data = json.loads(post_data.decode('utf-8'))
      debugg(f"Received JSON data: {json_data}")

      command = json_data.get('command')
      timeout = json_data.get('timeout', timeout_default)

      debugg(f"      my API Key: {DMS_API_KEY}")
      debugg(f"Received API Key: {api_key}")
      debugg(f"Received command: {command}")
      debugg(f"Received timeout: {timeout}")

      if api_key == DMS_API_KEY:
        if not command:
          response_message = {"status": "error", "error": "no command was passed"}
          logger(response_message['error'])
          raise ValueError(response_message['error'])

        else:
          try:
            # from here we could analyze and limit commands to be executed like remove unlink and rm, etc

            logger(f"Executing command: {command}")
            result = subprocess.run(command,
                                    shell=True,
                                    capture_output=True, # Capture stdout and stderr
                                    text=True,           # Decode stdout and stderr as text
                                    check=False,         # Do not raise an exception for non-zero exit codes
                                    timeout=timeout,     # timeout in seconds
                                    )
            debugg("result: {result}")  #  CompletedProcess(args='/usr/local/bin/setup alias list', returncode=0, stdout='...

            response_message = {
              "status": "success",
              'returncode': result.returncode,
              'stdout': result.stdout,
              'stderr': result.stderr
            }
            debugg(f"response_message: {response_message}")


          except Exception as e:
            response_message = {"status": "error", "error": str(e)}
            logger(response_message['error'])

      else:
        if DMS_API_KEY != 'missing':
          if api_key != 'missing':
            response_message = {"status": "error", "error": f"Invalid api_key: api_match: {str(api_key)}"}
          else:
            response_message = {"status": "error", "error": f"Missing api_key: api_miss"}
        else:
          response_message = {"status": "error", "error": f"DMS api_key unset: api_unset"}
        logger(response_message['error'])

      # 5. Send a successful response
      self.send_response(200)
      self.send_header('Content-type', 'application/json')
      self.end_headers()
      #logger(f"response_message: {response_message}")
      self.wfile.write(json.dumps(response_message).encode('utf-8'))

    except json.JSONDecodeError:
      # 6. Handle invalid JSON
      self.send_response(400) # Bad Request
      self.send_header('Content-type', 'application/json')
      self.end_headers()
      response_message = {"status": "error", "error": "Invalid JSON format"}
      logger(f"response_message: {response_message}")
      self.wfile.write(json.dumps(response_message).encode('utf-8'))

    except Exception as e:
      # 7. Handle other potential errors
      self.send_response(500) # Internal Server Error
      self.send_header('Content-type', 'application/json')
      self.end_headers()
      response_message = {"status": "error", "error": str(e)}
      logger(f"response_message: {response_message}")
      self.wfile.write(json.dumps(response_message).encode('utf-8'))


with socketserver.TCPServer((DMS_API_HOST, DMS_API_PORT), APIHandler) as httpd:
  logger(f"Serving at port {DMS_API_HOST}:{DMS_API_PORT}")
  httpd.serve_forever()
